name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Pulsar
      run: brew install pulsar

    - name: Install dependencies
      run: ppm install

    - name: Run tests
      run: pulsar --test spec
