name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - name: Install Pulsar dependencies on Linux
      run: sudo apt install -y libsecret-1-0
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Install Pulsar on macOS
      run: brew install pulsar
      if: ${{ matrix.os == 'macos-latest' }}
    - name: Install Pulsar on Linux
      uses: pulsar-edit/action-pulsar-dependency@v3
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Install package dependencies
      run: ppm install

    - name: Run tests
      uses: coactions/setup-xvfb@v1
      with:
        run: pulsar --test spec
