name: CI

on: [push]

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable, beta]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Atom
      uses: UziTech/action-setup-atom@v3
      with:
        version: ${{ matrix.channel }}

    - name: Install dependencies
      run: apm install

    - name: Run tests
      run: atom --test spec
