name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Pulsar
      uses: pulsar-edit/action-pulsar-dependency@v3

    - name: Install dependencies
      run: ppm install

    - name: Run tests
      uses: coactions/setup-xvfb@v1
      with:
        run: pulsar --test spec
